name: Angular CI

on:
  push:
    branches: [main, develop, feature/workflow]
  pull_request:
    branches: [main, develop, feature/workflow]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v5

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Rodar testes
        run: npx ng test --no-watch --no-progress --browsers=ChromeHeadless